### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by OvisMaximus** [jdavisonc/rasparmony#1]
I just tried to setup this project but I could not figure out how to get it up and running.

reproduce:
    git clone ...
    npm install
    export PORT=3333
    npm start

```
> rasparmony@0.0.0 start /home/pi/rasparmony
> node app.js
```

Console:
    WARNING: { [Error: Cannot find module '/home/pi/rasparmony/config/config.json'] code: 'MODULE_NOT_FOUND' }
    Rasparmony node has started on port 3333
    10.10.60.44 - - [Fri, 18 Dec 2015 19:43:48 GMT] "GET / HTTP/1.1" 404 - "-" "...browserid..."

Website:
    Cannot GET /

The only difference I see when I provide a config.json at the location named by the warning is a line in the log:
    &lt; Buffer 6c 69 72 63 64 3a 20 63 61 6e 27 74 20 6f 70 65 6e 20 6f 72 20 63 72 65 61 74 65 20 2f 76 61 72 2f 72 75 6e 2f 6c 69 72 63 2f 6c 69 72 63 64 2e 70 69 64 ...&gt;

**Comment by OvisMaximus** [comment]
Tried the development path:
- installed gulp
- called gulp
  gulp
  
  [21:05:34] Using gulpfile ~/rasparmony/gulpfile.js
  [21:05:34] Starting 'default'...
  [21:05:34] Starting 'build'...
  [21:05:34] Starting 'clean'...
  [21:05:35] Finished 'clean' after 981 ms
  [21:05:35] Starting 'html'...
  [21:05:35] Finished 'html' after 19 ms
  [21:05:35] Starting 'fonts'...
  [21:05:35] Starting 'images'...
  [21:05:35] Starting 'less'...
  [21:05:35] Finished 'less' after 54 ms
  [21:05:35] Starting 'js'...
  [21:05:36] Finished 'js' after 158 ms
  [21:05:45] Finished 'fonts' after 9.67 s
  [21:05:45] gulp-imagemin: Minified 0 images (saved 0 B - 0%)
  [21:05:45] Finished 'images' after 9.71 s
  [21:05:45] Finished 'build' after 11 s
  [21:05:45] Starting 'server'...
  [21:05:45] Finished 'server' after 149 ms
  [21:05:45] Starting 'watch'...
  [21:05:45] Finished 'watch' after 70 ms
  [21:05:45] Finished 'default' after 11 s
  livereload[tiny-lr] listening on 35729 ...
  
  events.js:72
      throw er; // Unhandled 'error' event
            ^
  Error: 'mobile-angular-ui/src/less/mobile-angular-ui.less' wasn't found in file                                                           /home/pi/rasparmony/src/less/app.less line no. 1

**Comment by jdavisonc** [comment]
Hi @OvisMaximus, sorry to hear that.
Do you copy a standard config.json file to config file ? You can do this:
`cp test/fixtures/config.json config/.`

The web should always run, the connection to lircd could not work depending on if you already have installed and configured.

**Comment by OvisMaximus** [comment]
lircd is running and well configured - open-source-universal-remote already works fine, but as you now, the layout and the lack of state. Hence the change to another port by the way.

I tried the config.json from the test fixtures, modified it, so that only the sections exist and also tried a modified version with ids that also exist in my lirc configuration.

The `Cannot GET /` is away, after calling gulp once. I believe, that some files are created or moved, when gulp is called. Adding up these observations lead me to these conclusions:
- the raw startup without development steps cannot work due to missing files
- for the build by bower are also files missing.

Below you'll find a list of all files.

After the call to gulp 'Rasparmony' and 'Menu' is rendered without any layout or CSS being obviously in effect. The Javascript console of the browser and the console log state that three referred files are not available: 

10.10.60.44 - - [Mon, 21 Dec 2015 20:13:27 GMT] "GET /css/app.min.css HTTP/1.1" 404 - "http://controlcenter:3333/"
10.10.60.44 - - [Mon, 21 Dec 2015 20:13:27 GMT] "GET /css/responsive.min.css HTTP/1.1" 404 - "http://controlcenter:3333/"
10.10.60.44 - - [Mon, 21 Dec 2015 20:13:27 GMT] "GET /js/app.min.js HTTP/1.1" 404 - "http://controlcenter:3333/"

Here is the output of `find . -type f | grep -v git | grep -v modules`:
    ./app.js
    ./Dockerfile
    ./src/less/variables.less
    ./src/less/app.less
    ./src/less/responsive.less
    ./src/less/mixins.less
    ./src/js/app.js
    ./src/js/controllers/main_controller.js
    ./src/templates/home.html
     ./src/templates/remote.html
    ./src/templates/sidebar.html
    ./src/templates/configuration.html
    ./src/html/index.html
    ./package.json
    ./README.md
    ./lirc.js
     ./www/index.html
    ./config/config.json
    ./config/irexecrc
    ./config/lircrc
    ./init.d/rasparmony
    ./bower.json
    ./findCodes.sh
    ./entrypoint.sh
    ./test/fixtures/config.json
    ./test/fixtures/remotes.json
    ./gulpfile.js
    ./.dockerignore

**Comment by jdavisonc** [comment]
Hi @OvisMaximus, I uploaded a few changes and fixes to let you build and run Rasparmony with or without development environment. Please let me know if it works for you.

Also, one of the last changes I made was to init lirc daemon from from Rasparmony node, this change let me configure LIRC based on config.json, IRC codes and reception code listeners. For now It doesn't support disable this action.

I'm glad that other people is trying to use Rasparmony, any feedback is welcome :)

**Comment by OvisMaximus** [comment]
Hi @jdavisonc, i gave it a try and yes, now the application comes up. I'm just starting to play around a little bit with the configuration.
